@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

skinparam shadowing false
skinparam ObjectFontColor #FFFFFF
skinparam ObjectAttributeFontColor #FFFFFF
skinparam ObjectBorderColor #FFFFFF

show objects
show members

object "<u>:HitListParser</u>" as HitListParser LOGIC_COLOR
object "<u>:AddCompanyCommandParser</u>" as AddCompanyCommandParser LOGIC_COLOR
object "<u>c:AddCompanyCommand</u>" as AddCompanyCommand LOGIC_COLOR
object "<u>toAdd:Company</u>" as Company MODEL_COLOR

HitListParser ..> AddCompanyCommandParser : creates >
AddCompanyCommandParser ..> AddCompanyCommand : creates >
AddCompanyCommand --> Company : contains >

Company : companyName = "Google"
Company : companyDescription = "Tech Company"
@enduml
