@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

skinparam shadowing false
skinparam ObjectFontColor #FFFFFF
skinparam ObjectAttributeFontColor #FFFFFF
skinparam ObjectBorderColor #FFFFFF

show objects
show members

object "<u>:LogicManager</u>" as LogicManager LOGIC_COLOR
object "<u>d:DeleteCompanyCommand</u>" as DeleteCompanyCommand LOGIC_COLOR
object "<u>:ModelManager</u>" as ModelManager MODEL_COLOR
object "<u>:HitList</u>" as HitList MODEL_COLOR
object "<u>:UniqueCompanyList</u>" as UniqueCompanyList MODEL_COLOR
object "<u>target:Company</u>" as Company MODEL_COLOR

LogicManager --> DeleteCompanyCommand : executes >
ModelManager --> HitList
HitList --> UniqueCompanyList
UniqueCompanyList --> Company : contains >

DeleteCompanyCommand : companyName = "Google"
Company : companyName = "Google"
Company : companyDescription = "Tech Company"
@enduml
