@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

skinparam shadowing false
skinparam ObjectFontColor #FFFFFF
skinparam ObjectAttributeFontColor #FFFFFF
skinparam ObjectBorderColor #FFFFFF

show objects
show members

object "<u>:ModelManager</u>" as ModelManager MODEL_COLOR
object "<u>:HitList</u>" as HitList MODEL_COLOR
object "<u>:UniqueCompanyList</u>" as UniqueCompanyList MODEL_COLOR

ModelManager --> HitList
HitList --> UniqueCompanyList

note right of UniqueCompanyList
  The Company object representing
  "Google" has been removed from
  the list and deleted from memory.
end note
@enduml
