@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

skinparam shadowing false
skinparam ObjectFontColor #FFFFFF
skinparam ObjectAttributeFontColor #FFFFFF
skinparam ObjectBorderColor #FFFFFF

show objects
show members

object "__:AddCompanyRoleCommandParser__" as Parser LOGIC_COLOR
object "__:AddCompanyRoleCommand__" as Command LOGIC_COLOR
object "__targetCompany:Name__" as TargetName MODEL_COLOR
object "__toAdd:Role__" as Role MODEL_COLOR

Parser ..> Command : creates >
Command *--> TargetName : holds >
Command *--> Role : holds >

TargetName : companyName = "Google"
Role : roleName = "Software Engineer"
Role : roleDescription = "Develops software solutions"

@enduml
