@startuml role-add-execution /' Renames the file to kebab-case when exported as an image.'/
!include ../style.puml
skinparam ArrowFontStyle plain

skinparam shadowing false
skinparam ObjectFontColor #FFFFFF
skinparam ObjectAttributeFontColor #FFFFFF
skinparam ObjectBorderColor #FFFFFF

show objects
show members

object "<u>c:AddCompanyRoleCommand</u>" as Command LOGIC_COLOR
object "<u>m:ModelManager</u>" as Model MODEL_COLOR
object "<u>h:HitList</u>" as HitList MODEL_COLOR
object "<u>google:Company</u>" as Company MODEL_COLOR
object "<u>toAdd:Role</u>" as Role MODEL_COLOR

Command -right-> Model : executes on >
Command *--> Role : holds >
Model --> HitList
HitList *--> Company

Company : companyName = "Google"
Company : companyDescription = "Tech Company"
Role : roleName = "Software Engineer"
Role : roleDescription = "Develops software solutions"

@enduml
