@startuml role-add-post-execution /' Renames the file to kebab-case when exported as an image.'/
!include ../style.puml
skinparam ArrowFontStyle plain

skinparam shadowing false
skinparam ObjectFontColor #FFFFFF
skinparam ObjectAttributeFontColor #FFFFFF
skinparam ObjectBorderColor #FFFFFF

show objects
show members

object "<u>m:ModelManager</u>" as Model MODEL_COLOR
object "<u>h:HitList</u>" as HitList MODEL_COLOR
object "<u>google:Company</u>" as Company MODEL_COLOR
object "<u>r:RoleList</u>" as RoleList MODEL_COLOR
object "<u>newRole:Role</u>" as Role MODEL_COLOR

Model -right-> HitList
HitList *--> Company
Company *--> RoleList
RoleList *--> Role

Company : companyName = "Google"
Company : companyDescription = "Tech Company"
Role : roleName = "Software Engineer"
Role : roleDescription = "Develops software solutions"

@enduml
