@startuml role-add-parsing /' Renames the file to kebab-case when exported as an image.'/
!include ../style.puml
skinparam ArrowFontStyle plain

skinparam shadowing false
skinparam ObjectFontColor #FFFFFF
skinparam ObjectAttributeFontColor #FFFFFF
skinparam ObjectBorderColor #FFFFFF

show objects
show members

object "<u>:AddCompanyRoleCommandParser</u>" as Parser LOGIC_COLOR
object "<u>:AddCompanyRoleCommand</u>" as Command LOGIC_COLOR
object "<u>targetCompany:Name</u>" as TargetName MODEL_COLOR
object "<u>toAdd:Role</u>" as Role MODEL_COLOR

Parser ..> Command : creates >
Command *--> TargetName : holds >
Command *--> Role : holds >

TargetName : companyName = "Google"
Role : roleName = "Software Engineer"
Role : roleDescription = "Develops software solutions"

@enduml
