@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

skinparam shadowing false
skinparam ObjectFontColor #FFFFFF
skinparam ObjectAttributeFontColor #FFFFFF
skinparam ObjectBorderColor #FFFFFF

show objects
show members

object "__c:AddCompanyRoleCommand__" as Command LOGIC_COLOR
object "__m:ModelManager__" as Model MODEL_COLOR
object "__h:HitList__" as HitList MODEL_COLOR
object "__google:Company__" as Company MODEL_COLOR
object "__toAdd:Role__" as Role MODEL_COLOR

Command -right-> Model : executes on >
Command *--> Role : holds >
Model --> HitList
HitList *--> Company

Company : companyName = "Google"
Company : companyDescription = "Tech Company"
Role : roleName = "Software Engineer"
Role : roleDescription = "Develops software solutions"

@enduml
