@startuml group-add-execution
!include ../style.puml
skinparam ArrowFontStyle plain

skinparam shadowing false
skinparam ObjectFontColor #FFFFFF
skinparam ObjectAttributeFontColor #FFFFFF
skinparam ObjectBorderColor #FFFFFF

show objects
show members

object ":LogicManager" as LogicManager LOGIC_COLOR
object "c:AddGroupCommand" as AddGroupCommand LOGIC_COLOR
object "toAdd:Group" as Group MODEL_COLOR
object "memberNames:Set<Name>" as MemberNames MODEL_COLOR
object ":ModelManager" as ModelManager MODEL_COLOR

LogicManager --> AddGroupCommand : executes >
AddGroupCommand --> Group : contains >
AddGroupCommand --> MemberNames : contains >
AddGroupCommand ..> ModelManager : passes group to >

Group : groupName = "Students"
MemberNames : {"Alex Yeoh", "Bernice Yu"}
@enduml
