@startuml group-add-post-execution
!include ../style.puml
skinparam ArrowFontStyle plain

skinparam shadowing false
skinparam ObjectFontColor #FFFFFF
skinparam ObjectAttributeFontColor #FFFFFF
skinparam ObjectBorderColor #FFFFFF

show objects
show members

object "<u>:ModelManager</u>" as ModelManager MODEL_COLOR
object "<u>:HitList</u>" as HitList MODEL_COLOR
object "<u>:UniqueGroupList</u>" as UniqueGroupList MODEL_COLOR
object "<u>:Group</u>" as Group MODEL_COLOR

ModelManager --> HitList
HitList --> UniqueGroupList
UniqueGroupList --> Group : contains >

Group : groupName = "Students"

note right of Group
Members may include:
Alex Yeoh
Bernice Yu
end note
@enduml
