@startuml group-add-post-execution
!include ../style.puml
skinparam ArrowFontStyle plain

skinparam shadowing false
skinparam ObjectFontColor #FFFFFF
skinparam ObjectAttributeFontColor #FFFFFF
skinparam ObjectBorderColor #FFFFFF

show objects
show members

object ":ModelManager" as ModelManager MODEL_COLOR
object ":HitList" as HitList MODEL_COLOR
object ":UniqueGroupList" as UniqueGroupList MODEL_COLOR
object ":Group" as Group MODEL_COLOR

ModelManager --> HitList
HitList --> UniqueGroupList
UniqueGroupList --> Group : contains >

Group : groupName = "Students"

note right of Group
Members may include:
Alex Yeoh
Bernice Yu
end note
@enduml
