@startuml unassign-group/GroupUnassignSequenceDiagram /' Renames the file to kebab-case when exported as an image.'/
!include ../style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":HitListParser" as HitListParser LOGIC_COLOR
participant ":UnassignGroupCommandParser" as UnassignGroupCommandParser LOGIC_COLOR
participant "c:UnassignGroupCommand" as UnassignGroupCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("grpunassign /n Alex /g Students")
activate LogicManager

LogicManager -> HitListParser : parseCommand("grpunassign /n Alex /g Students")
activate HitListParser

create UnassignGroupCommandParser
HitListParser -> UnassignGroupCommandParser
activate UnassignGroupCommandParser

UnassignGroupCommandParser --> HitListParser
deactivate UnassignGroupCommandParser

HitListParser -> UnassignGroupCommandParser : parse(" /n Alex /g Students")
activate UnassignGroupCommandParser

create UnassignGroupCommand
UnassignGroupCommandParser -> UnassignGroupCommand
activate UnassignGroupCommand

UnassignGroupCommand --> UnassignGroupCommandParser : c
deactivate UnassignGroupCommand

UnassignGroupCommandParser --> HitListParser : c
deactivate UnassignGroupCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
UnassignGroupCommandParser -[hidden]-> HitListParser
destroy UnassignGroupCommandParser

HitListParser --> LogicManager : c
deactivate HitListParser

LogicManager -> UnassignGroupCommand : execute(m)
activate UnassignGroupCommand

UnassignGroupCommand -> Model : getPersonsByName(personName)
activate Model
Model --> UnassignGroupCommand : matchedPersons
deactivate Model

UnassignGroupCommand -> Model : getGroup(groupName)
activate Model
Model --> UnassignGroupCommand : targetGroup
deactivate Model

UnassignGroupCommand -> Model : targetGroup.removeMember(contact)
activate Model
Model --> UnassignGroupCommand
deactivate Model

UnassignGroupCommand -> Model : updateFilteredPersonList(predicate)
activate Model
Model --> UnassignGroupCommand
deactivate Model

create CommandResult
UnassignGroupCommand -> CommandResult
activate CommandResult

CommandResult --> UnassignGroupCommand : r
deactivate CommandResult

UnassignGroupCommand --> LogicManager : r
deactivate UnassignGroupCommand

[<--LogicManager
deactivate LogicManager
@enduml
