@startuml unassign-group/GroupUnassignExecution /' Renames the file to kebab-case when exported as an image.'/
!include ../style.puml
skinparam ArrowFontStyle plain

skinparam shadowing false
skinparam ObjectFontColor #FFFFFF
skinparam ObjectAttributeFontColor #FFFFFF
skinparam ObjectBorderColor #FFFFFF

show objects
show members

object ":LogicManager" as LogicManager LOGIC_COLOR
object "c:UnassignGroupCommand" as UnassignGroupCommand LOGIC_COLOR
object "targetPerson:Person" as Person MODEL_COLOR
object "targetGroup:Group" as Group MODEL_COLOR
object ":ModelManager" as ModelManager MODEL_COLOR

LogicManager --> UnassignGroupCommand : executes >
UnassignGroupCommand --> Person : contains >
UnassignGroupCommand --> Group : contains >
UnassignGroupCommand ..> ModelManager : passes targetGroup to >
@enduml
