@startuml unassign-group/GroupUnassignExecution /' Renames the file to kebab-case when exported as an image.'/
!include ../style.puml
skinparam ArrowFontStyle plain

skinparam shadowing false
skinparam ObjectFontColor #FFFFFF
skinparam ObjectAttributeFontColor #FFFFFF
skinparam ObjectBorderColor #FFFFFF

show objects
show members

object "<u>:LogicManager</u>" as LogicManager LOGIC_COLOR
object "<u>c:UnassignGroupCommand</u>" as UnassignGroupCommand LOGIC_COLOR
object "<u>targetPerson:Person</u>" as Person MODEL_COLOR
object "<u>targetGroup:Group</u>" as Group MODEL_COLOR
object "<u>:ModelManager</u>" as ModelManager MODEL_COLOR

LogicManager --> UnassignGroupCommand : executes >
UnassignGroupCommand --> Person : contains >
UnassignGroupCommand --> Group : contains >
UnassignGroupCommand ..> ModelManager : passes targetGroup to >
@enduml
