@startuml assign-group/GroupAssignExecution /' Renames the file to kebab-case when exported as an image.'/
!include ../style.puml
skinparam ArrowFontStyle plain

skinparam shadowing false
skinparam ObjectFontColor #FFFFFF
skinparam ObjectAttributeFontColor #FFFFFF
skinparam ObjectBorderColor #FFFFFF

show objects
show members

object "<u>:LogicManager</u>" as LogicManager LOGIC_COLOR
object "<u>c:AssignGroupCommand</u>" as AssignGroupCommand LOGIC_COLOR
object "<u>targetPerson:Person</u>" as Person MODEL_COLOR
object "<u>targetGroup:Group</u>" as Group MODEL_COLOR
object "<u>:ModelManager</u>" as ModelManager MODEL_COLOR

LogicManager --> AssignGroupCommand : executes >
AssignGroupCommand --> Person : contains >
AssignGroupCommand --> Group : contains >
AssignGroupCommand ..> ModelManager : passes targetGroup to >
@enduml
