@startuml person-delete-execution
!include ../style.puml
skinparam ArrowFontStyle plain

skinparam shadowing false
skinparam ObjectFontColor #FFFFFF
skinparam ObjectAttributeFontColor #FFFFFF
skinparam ObjectBorderColor #FFFFFF

show objects
show members

object ":LogicManager" as LogicManager LOGIC_COLOR
object "c:DeleteCommand" as DeleteCommand LOGIC_COLOR
object "targetName:Name" as Name MODEL_COLOR
object ":ModelManager" as ModelManager MODEL_COLOR

LogicManager --> DeleteCommand : executes >
DeleteCommand --> Name : contains >
DeleteCommand ..> ModelManager : passes target to >

Name : fullName = "John Doe"
@enduml
