@startuml person-delete-parsing
!include ../style.puml
skinparam ArrowFontStyle plain

skinparam shadowing false
skinparam ObjectFontColor #FFFFFF
skinparam ObjectAttributeFontColor #FFFFFF
skinparam ObjectBorderColor #FFFFFF

show objects
show members

object "<u>:HitListParser</u>" as HitListParser LOGIC_COLOR
object "<u>:DeleteCommandParser</u>" as DeleteCommandParser LOGIC_COLOR
object "<u>c:DeleteCommand</u>" as DeleteCommand LOGIC_COLOR
object "<u>targetName:Name</u>" as Name MODEL_COLOR

HitListParser ..> DeleteCommandParser : creates >
DeleteCommandParser ..> DeleteCommand : creates >
DeleteCommand --> Name : contains >

Name : fullName = "John Doe"
@enduml
