@startuml group-delete-execution
!include ../style.puml
skinparam ArrowFontStyle plain

skinparam shadowing false
skinparam ObjectFontColor #FFFFFF
skinparam ObjectAttributeFontColor #FFFFFF
skinparam ObjectBorderColor #FFFFFF

show objects
show members

object "<u>:LogicManager</u>" as LogicManager LOGIC_COLOR
object "<u>c:DeleteGroupCommand</u>" as DeleteGroupCommand LOGIC_COLOR
object "<u>toDelete:Group</u>" as Group MODEL_COLOR
object "<u>:ModelManager</u>" as ModelManager MODEL_COLOR

LogicManager --> DeleteGroupCommand : executes >
DeleteGroupCommand --> Group : contains >
DeleteGroupCommand ..> ModelManager : passes target to >

Group : groupName = "Students"
@enduml
