@startuml group-delete-parsing
!include ../style.puml
skinparam ArrowFontStyle plain

skinparam shadowing false
skinparam ObjectFontColor #FFFFFF
skinparam ObjectAttributeFontColor #FFFFFF
skinparam ObjectBorderColor #FFFFFF

show objects
show members

object "<u>:HitListParser</u>" as HitListParser LOGIC_COLOR
object "<u>:DeleteGroupCommandParser</u>" as DeleteGroupCommandParser LOGIC_COLOR
object "<u>c:DeleteGroupCommand</u>" as DeleteGroupCommand LOGIC_COLOR
object "<u>toDelete:Group</u>" as Group MODEL_COLOR

HitListParser ..> DeleteGroupCommandParser : creates >
DeleteGroupCommandParser ..> DeleteGroupCommand : creates >
DeleteGroupCommand --> Group : contains >

Group : groupName = "Students"
@enduml
