@startuml undo-sequence-diagram-logic /' Renames the file to kebab-case when exported as an image.'/
!include ../style.puml

skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":HitListParser" as HitListParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> HitListParser : parseCommand(undo)
activate HitListParser

create UndoCommand
HitListParser -> UndoCommand
activate UndoCommand

UndoCommand --> HitListParser
deactivate UndoCommand

HitListParser --> LogicManager : u
deactivate HitListParser

LogicManager -> UndoCommand : execute(m)
activate UndoCommand

UndoCommand -> Model : undoHitList()
activate Model

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
