@startuml list-execution /' Renames the file to kebab-case when exported as an image.'/
!include ../style.puml
skinparam ArrowFontStyle plain

skinparam shadowing false
skinparam ObjectFontColor #FFFFFF
skinparam ObjectAttributeFontColor #FFFFFF
skinparam ObjectBorderColor #FFFFFF

show objects
show members

object "<u>:LogicManager</u>" as LogicManager LOGIC_COLOR
object "<u>l:ListCommand</u>" as Command LOGIC_COLOR
object "<u>:ModelManager</u>" as ModelManager MODEL_COLOR
object "<u>:Predicate<Person></u>" as Predicate LOGIC_COLOR

LogicManager --> Command : executes >
Command *--> Predicate : holds >
Command ..> ModelManager : passes Predicate to >
@enduml
