@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

show objects

object "<u>:LogicManager</u>" as LogicManager LOGIC_COLOR
object "<u>d:DeleteCompanyRoleCommand</u>" as Command LOGIC_COLOR
object "<u>:ModelManager</u>" as ModelManager MODEL_COLOR
object "<u>:HitList</u>" as HitList MODEL_COLOR
object "<u>targetCompany:Company</u>" as Company MODEL_COLOR
object "<u>:RoleList</u>" as RoleList MODEL_COLOR
object "<u>targetRole:Role</u>" as Role MODEL_COLOR

LogicManager --> "1" Command : executes >
ModelManager --> "1" HitList
HitList *--> "*" Company : contains >
Company *--> "1" RoleList
RoleList *--> "*" Role : contains >

Command : targetCompanyName = "Google"
Command : targetRoleName = "Software Engineer"
Company : name = "Google"
Role : name = "Software Engineer"
@enduml
