@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

skinparam shadowing false
skinparam ObjectFontColor #FFFFFF
skinparam ObjectAttributeFontColor #FFFFFF
skinparam ObjectBorderColor #FFFFFF

show objects
show members

object "<u>:LogicManager</u>" as LogicManager LOGIC_COLOR
object "<u>d:DeleteCompanyRoleCommand</u>" as Command LOGIC_COLOR
object "<u>:ModelManager</u>" as ModelManager MODEL_COLOR
object "<u>:HitList</u>" as HitList MODEL_COLOR
object "<u>targetCompany:Company</u>" as Company MODEL_COLOR
object "<u>:RoleList</u>" as RoleList MODEL_COLOR
object "<u>targetRole:Role</u>" as Role MODEL_COLOR

LogicManager --> Command : executes >
ModelManager --> HitList
HitList *--> Company : contains >
Company *--> RoleList
RoleList *--> Role : contains >

Command : companyName = "Google"
Command : roleName = "Software Engineer"
Company : companyName = "Google"
Role : roleName = "Software Engineer"
@enduml
