@startuml role-delete-sequence-diagram-logic
!include ../style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":HitListParser" as HitListParser LOGIC_COLOR
participant ":DeleteCompanyRoleCommandParser" as DeleteCompanyRoleCommandParser LOGIC_COLOR
participant "d:DeleteCompanyRoleCommand" as DeleteCompanyRoleCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("roledel /c Google /r SE")
activate LogicManager

LogicManager -> HitListParser : parseCommand(...)
activate HitListParser

create DeleteCompanyRoleCommandParser
HitListParser -> DeleteCompanyRoleCommandParser
activate DeleteCompanyRoleCommandParser

DeleteCompanyRoleCommandParser --> HitListParser
deactivate DeleteCompanyRoleCommandParser

HitListParser -> DeleteCompanyRoleCommandParser : parse(" /c Google /r SE")
activate DeleteCompanyRoleCommandParser

create DeleteCompanyRoleCommand
DeleteCompanyRoleCommandParser -> DeleteCompanyRoleCommand
activate DeleteCompanyRoleCommand

DeleteCompanyRoleCommand --> DeleteCompanyRoleCommandParser : d
deactivate DeleteCompanyRoleCommand

DeleteCompanyRoleCommandParser --> HitListParser : d
deactivate DeleteCompanyRoleCommandParser
destroy DeleteCompanyRoleCommandParser

HitListParser --> LogicManager : d
deactivate HitListParser

LogicManager -> DeleteCompanyRoleCommand : execute(m)
activate DeleteCompanyRoleCommand

DeleteCompanyRoleCommand -> Model : getCompany(companyName)
activate Model
Model --> DeleteCompanyRoleCommand : company (optional)
deactivate Model

DeleteCompanyRoleCommand -> DeleteCompanyRoleCommand : findRoleToDelete()
activate DeleteCompanyRoleCommand
DeleteCompanyRoleCommand --> DeleteCompanyRoleCommand : roleToDelete
deactivate DeleteCompanyRoleCommand

DeleteCompanyRoleCommand -> DeleteCompanyRoleCommand : company.getUniqueRoleList().remove(roleToDelete)

DeleteCompanyRoleCommand -> Model : updateRoleList(companyName)
activate Model

create CommandResult
DeleteCompanyRoleCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCompanyRoleCommand : r
deactivate CommandResult

DeleteCompanyRoleCommand --> LogicManager : r
deactivate DeleteCompanyRoleCommand

[<--LogicManager
deactivate LogicManager
@enduml
