@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

skinparam shadowing false
skinparam ObjectFontColor #FFFFFF
skinparam ObjectAttributeFontColor #FFFFFF
skinparam ObjectBorderColor #FFFFFF

show objects
show members

object "<u>:ModelManager</u>" as ModelManager MODEL_COLOR
object "<u>:HitList</u>" as HitList MODEL_COLOR
object "<u>targetCompany:Company</u>" as Company MODEL_COLOR
object "<u>:RoleList</u>" as RoleList MODEL_COLOR

ModelManager --> HitList
HitList *--> Company : contains >
Company *--> RoleList

note right of RoleList
  The Role object representing
  "Software Engineer" has been removed
  from the list and deleted from memory.
end note

Company : name = "Google"
@enduml
