@startuml
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12

start
:User executes command;

if () then ([Command is valid])
  :Parse name, phone,\noptional email and address;
  :Create new Person object;
  if () then ([Name does not exist in HitList])
    :Add Person to Model;
    :Save updated HitList to Storage;
    :Display success message to User;
  else ([Duplicate name])
    :Display duplicate contact error;
  endif
else ([Command is invalid])
  :Display invalid command format error;
endif

stop
@enduml
