@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":HitListParser" as HitListParser LOGIC_COLOR
participant ":AddCommandParser" as AddCommandParser LOGIC_COLOR
participant "c:AddCommand" as AddCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("add /n John Doe /p 98765432 ...")
activate LogicManager

LogicManager -> HitListParser : parseCommand("add /n John Doe /p 98765432 ...")
activate HitListParser

create AddCommandParser
HitListParser -> AddCommandParser
activate AddCommandParser

AddCommandParser --> HitListParser
deactivate AddCommandParser

HitListParser -> AddCommandParser : parse(" /n John Doe /p 98765432 ...")
activate AddCommandParser

create AddCommand
AddCommandParser -> AddCommand
activate AddCommand

AddCommand --> AddCommandParser : c
deactivate AddCommand

AddCommandParser --> HitListParser : c
deactivate AddCommandParser
AddCommandParser -[hidden]-> HitListParser
destroy AddCommandParser

HitListParser --> LogicManager : c
deactivate HitListParser

LogicManager -> AddCommand : execute(m)
activate AddCommand

AddCommand -> Model : addPerson(toAdd)
activate Model
Model --> AddCommand
deactivate Model

AddCommand --> LogicManager : result
deactivate AddCommand
AddCommand -[hidden]-> LogicManager
destroy AddCommand

[<-- LogicManager
deactivate LogicManager
@enduml
