@startuml person-add-parsing
!include ../style.puml
skinparam ArrowFontStyle plain

skinparam shadowing false
skinparam ObjectFontColor #FFFFFF
skinparam ObjectAttributeFontColor #FFFFFF
skinparam ObjectBorderColor #FFFFFF

show objects
show members

object "<u>:HitListParser</u>" as HitListParser LOGIC_COLOR
object "<u>:FindCommandParser</u>" as FindCommandParser LOGIC_COLOR
object "<u>c:FindCommand</u>" as FindCommand LOGIC_COLOR
object "<u>:PersonMatchesFindPredicate</u>" as PersonMatchesFindPredicate MODEL_COLOR

HitListParser ..> FindCommandParser : creates >
FindCommandParser ..> FindCommand : creates >
FindCommand --> PersonMatchesFindPredicate : contains >

PersonMatchesFindPredicate : nameKeywords = ["Alex", "Lee"]
@enduml
