@startuml person-add-post-execution
!include ../style.puml
skinparam ArrowFontStyle plain

skinparam shadowing false
skinparam ObjectFontColor #FFFFFF
skinparam ObjectAttributeFontColor #FFFFFF
skinparam ObjectBorderColor #FFFFFF

show objects
show members

object "<u>:ModelManager</u>" as ModelManager MODEL_COLOR
object "<u>:HitList</u>" as HitList MODEL_COLOR
object "<u>filteredPersons:FilteredList<Person></u>" as FilteredPersons MODEL_COLOR
object "<u>:PersonMatchesFindPredicate</u>" as Predicate MODEL_COLOR

ModelManager --> HitList
ModelManager --> FilteredPersons : contains >
FilteredPersons ..> Predicate : uses >

Predicate : nameKeywords = ["Alex", "Lee"]
@enduml
